### ISSUE TITLE
Add "convert USD to TWD" functionality

### ISSUE THREAD

**Issue by komali2** [komali2/quick-taiwan-conversions#3]
Note that this isn't TWD to USD, keep it simple.

We want there to be a way for people to convert USD to TWD. 

This will probably be a very simple [input field](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) that updates a [vue component state](https://v3.vuejs.org/guide/forms.html), which goes on to update the text inside a DIV somewhere with a [computed property](https://v3.vuejs.org/guide/computed.html). 

The page can look simple, like this:

```
      __________________
     |       (input USD here)  |
     |__________________|

      |  button to click to convert, or the conversion can happen onchange (see vue docs) | 

      simple plaintext output 
```

Don't worry about styling.

I would probably tackle this by

1. Creating a new, nearly-empty (they have to have at least 1 HTML element in them) vue component file (see HelloWorld as an example)
2. Import that new component into App.vue or whatever the main view is
3. Add an input field to the new component
4. Tie the input field to component state with v-model (see links above)
5. Make a "computed" property that takes in the step 4 component state property, and outputs that number * 30 (keep it simple for now)
6. Make that computed property render using `{{}}` somewhere else in the component

Feel free to ask for help

**Comment by MorganELLiot** [comment]
This was a lot of fun to work through, thanks a lot for writing up this issue. It took me a while to figure out the formatting in Vue but I think I'm slowly getting the hang of it. Exciting when things click!

**Comment by komali2** [comment]
Glad to hear it. Hindsight, it may be easier to, before doing the `computed` task, instead just make it so that the input into the input field is also displayed elsewhere and updates dynamically. That'll mean simply `{{putting_in_here}}` the state variable.

**Comment by komali2** [comment]
this is done right?
